name: Demo
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-20.04
    steps:
      - name: Print to console  
        run: echo Hello Alex!
      - name: Print a few lines
        run: |
          echo first
          echo second
          
    
